services:
  app:
    build:
      dockerfile: node.dockerfile
      context: .
      args:
        NUXT_PUBLIC_SHOPWARE_ENDPOINT: ${NUXT_PUBLIC_SHOPWARE_ENDPOINT:-https://my.shop/store-api}
        NUXT_PUBLIC_SHOPWARE_ACCESS_TOKEN: ${NUXT_PUBLIC_SHOPWARE_ACCESS_TOKEN:-TOKEN}
    user: node
    env_file:
      - .env
    ports:
      - '3000:3000'
      - '24678:24678'